version: '3.8'

services:
  dev-postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mtg-deck-builder-dev-db
    ports:
      - '5455:5432'
    volumes:
      - ./mtg-deck-builder-dev-db:/var/lib/postgresql/data
